apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: client
spec:
  rules:
    - host: client-wrichter-dhbw-exercise-1.apps.osd-evalcluster.v0z2.p1.openshiftapps.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: client
              servicePort: 3000
