apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: client
    app.kubernetes.io/component: client
    app.kubernetes.io/instance: client
    app.kubernetes.io/part-of: dhbw-exercise-1
  name: client
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: replace/me/client:latest
    importPolicy:
      scheduled: true
    name: latest
    referencePolicy:
      type: Source